package io.github.kdroidfilter.seforimapp.framework.database

import java.io.File

/**
 * Manages database versioning and compatibility checks.
 *
 * The system uses release timestamp format: yyyyMMddHHmmss (UTC)
 * Generated by WriteReleaseInfo.kt in the generator module.
 */
object DatabaseVersionManager {
    /**
     * Minimum required database version for this application release.
     * This should be updated when database schema or data structure changes.
     */
    private const val MINIMUM_REQUIRED_VERSION = "20260601094341"

    /**
     * Gets the current database version by reading the release_info.txt file
     * located next to the database file.
     *
     * @return Database version string (yyyyMMddHHmmss) or null if not found
     */
    fun getCurrentDatabaseVersion(): String? {
        return try {
            val dbPath = getDatabasePath()
            val dbFile = File(dbPath)

            // Look for release_info.txt in the same directory as the database
            val versionFile = File(dbFile.parentFile, "release_info.txt")

            if (!versionFile.exists()) {
                return null
            }

            versionFile.readText().trim()
        } catch (e: Exception) {
            null
        }
    }

    /**
     * Checks if the current database version meets the minimum requirement.
     *
     * @return true if database version is compatible, false otherwise
     */
    fun isDatabaseVersionCompatible(): Boolean {
        val currentVersion = getCurrentDatabaseVersion() ?: return false
        return isVersionCompatible(currentVersion, MINIMUM_REQUIRED_VERSION)
    }

    /**
     * Compares two version strings in yyyyMMddHHmmss format.
     *
     * @param currentVersion Current database version
     * @param requiredVersion Minimum required version
     * @return true if currentVersion >= requiredVersion
     */
    private fun isVersionCompatible(
        currentVersion: String,
        requiredVersion: String,
    ): Boolean {
        return try {
            // Both versions should be in yyyyMMddHHmmss format (14 digits)
            if (currentVersion.length != 14 || requiredVersion.length != 14) {
                return false
            }

            // Compare as numbers (timestamp comparison)
            currentVersion.toLong() >= requiredVersion.toLong()
        } catch (e: Exception) {
            false
        }
    }

    /**
     * Gets the minimum required database version.
     */
    fun getMinimumRequiredVersion(): String = MINIMUM_REQUIRED_VERSION

    /**
     * Checks if a database exists at the configured path.
     */
    fun isDatabaseConfigured(): Boolean =
        try {
            val dbPath = getDatabasePath()
            File(dbPath).exists()
        } catch (e: Exception) {
            false
        }

    /**
     * Gets a human-readable representation of a version timestamp.
     *
     * @param version Version string in yyyyMMddHHmmss format
     * @return Human-readable date string or the original version if parsing fails
     */
    fun formatVersionForDisplay(version: String): String =
        try {
            if (version.length == 14) {
                val year = version.substring(0, 4)
                val month = version.substring(4, 6)
                val day = version.substring(6, 8)
                val hour = version.substring(8, 10)
                val minute = version.substring(10, 12)
                val second = version.substring(12, 14)

                "$day/$month/$year $hour:$minute:$second"
            } else {
                version
            }
        } catch (e: Exception) {
            version
        }
}
